Algoritmo "exemplo2"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//Pergubte um número ao usuário e informe
//Se este número é par ou impar
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(num)

se (num%2 = 0) entao
   escreva("O número",num," é par")
senao
     escreva("O número",num," é ímpar")
fimse
Fimalgoritmo
