Algoritmo "questao18"
//Fazer um algoritmo
//que exiba o valor da soma dos números que existem no intervalo de 0 a 50.
Var
// Seção de Declarações das variáveis 
contador, acumulador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para contador de 0 ate 50 passo 1 faca
     acumulador <- acumulador + contador
fimpara

escreval("A soma dos números que existem no intervalo de 0 a 50 é = ", acumulador)

Fimalgoritmo