Algoritmo "questao23"
//Fazer um algoritmo que
//pergunte 20 números e ao final exiba a média destes 20 números.
Var
// Seção de Declarações das variáveis 
contador, num, acumulador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 20 passo 1 faca
     escreval("Insira um número: ")
     leia(num)
     acumulador <- acumulador + num
fimpara

escreval("A média destes 20 números é =", acumulador/20)

Fimalgoritmo