Algoritmo "questao03"
//Desenvolver um programa que apresente os quadrados dos números inteiros de 15 a 200.

Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 15

enquanto (contador <= 200) faca
         escreval("O quandrado de ", contador, " é", contador^2)
         contador <- contador + 1
fimenquanto

Fimalgoritmo