Algoritmo "questao03"
//Desenvolver um programa que apresente o fatorial de um número qualquer
Var
// Seção de Declarações das variáveis 
contador, acumulador, num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Insira um número: ")
leia(num)

acumulador <- 1

para contador de 1 ate num passo 1 faca
     acumulador <- contador * acumulador
fimpara

 escreval ("O fatorial de ", num, " é = ", acumulador)
Fimalgoritmo