Algoritmo "questao04"
//Desenvolver um programa que apresente os resultados de uma tabuada
//de um número qualquer.
Var
// Seção de Declarações das variáveis 

num, contador, tabuada: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira um número: ")
leia(num)

para contador de 1 ate 10 passo 1 faca
     tabuada <- num * contador
     escreval (num," x ", contador, " = ", num * contador)
fimpara

Fimalgoritmo