Algoritmo "questao06"
//Desenvolver um programa que apresente as potências de 2, variando de 0 a 10.
Var
// Seção de Declarações das variáveis 

contador: inteiro
poten: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para contador de 0 ate 10 passo 1 faca
     poten <- 2 ^ contador
     escreval ("2 ^ ", contador, " = ", poten)
     contador <- contador + 1
fimpara

Fimalgoritmo